ALTER TYPE "QuestionStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "QuestionStatus" ADD VALUE IF NOT EXISTS 'SELECTED';
ALTER TYPE "QuestionStatus" ADD VALUE IF NOT EXISTS 'RESEARCHING';
ALTER TYPE "QuestionStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
